### ISSUE TITLE
no browser interaction possible in recorded rectangle

### ISSUE THREAD

**Issue by derblub** [lolilolicon/FFcast#14]
This is the command I'm using:
```bash
ffcast -s % ffmpeg -f x11grab -show_region 1 -framerate 25 -video_size %s -i %D+%c -codec:v libx264 -b:v 20000k -vf crop="iw-mod(iw\\,2):ih-mod(ih\\,2)"
```
After selecting the rectangle I want to record, the selected part just freezes and no more animations or interaction is possible.

Is there anything I'm doing wrong? It's already quite some time when I used ffcast last, but I think I was able to interact with the browser below the recorded rectangle, right?

**Comment by lolilolicon** [comment]
The problem appears to be with the `-show_region` option; `-show_region 0` may serve as a workaround for you, for now?

The last ffmpeg version I have tested without this problem is 2.4.4. The issue must have been introduced in ffmpeg release 2.5.
In any case, I think it's this issue reported upstream:
https://trac.ffmpeg.org/ticket/4164
And the fix:
https://github.com/FFmpeg/FFmpeg/commit/0ae37e46

Let's hope it gets into a ffmpeg release soon.

**Comment by derblub** [comment]
Tested and confirmed.
Without the border, interaction is possible again.

Thanks for the workaround - can live with that for now :)

**Comment by lolilolicon** [comment]
I have applied the patch to ffmpeg 2.5.4 and it fixes the issue; I'm sure they'll have fixed it in the next release (:
